"""Services module for Australian Investment Analyzer"""
from .tax_constants import *

__all__ = [
    'HISTORICAL_TAX_BRACKETS',
    'PERSONAL_TAX_BRACKETS_2024_25',
    'PERSONAL_TAX_BRACKETS_2025_26',
    'HISTORICAL_COMPANY_RATES',
    'COMPANY_TAX_RATE_BASE',
    'COMPANY_TAX_RATE_FULL',
    'MEDICARE_LEVY_RATE',
    'MEDICARE_LEVY_THRESHOLD',
    'CGT_DISCOUNT_INDIVIDUAL',
    'CGT_DISCOUNT_SMSF',
    'SMSF_CONCESSIONAL_CAP',
    'SMSF_NON_CONCESSIONAL_CAP',
    'SMSF_BRING_FORWARD_CAP',
    'SMSF_TOTAL_SUPER_BALANCE_LIMIT',
    'SMSF_TAX_RATE',
    'SMSF_PENSION_TAX_RATE',
    'DIV_293_THRESHOLD',
]
