"""
PDF Report Generator for AdviceOS
Generates compliance reports, audit trails, and client files in PDF format.
"""

import os
import io
import uuid
from datetime import datetime, timezone
from typing import Optional, Dict, Any
from fastapi import APIRouter, HTTPException
from fastapi.responses import StreamingResponse
from motor.motor_asyncio import AsyncIOMotorClient
import logging

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/reports/pdf", tags=["PDF Reports"])

# MongoDB connection
MONGO_URL = os.environ.get("MONGO_URL", "mongodb://localhost:27017")
DB_NAME = os.environ.get("DB_NAME", "wealth_command")
client = AsyncIOMotorClient(MONGO_URL)
db = client[DB_NAME]

# Collections
scenarios_col = db["scenarios"]
compliance_checks_col = db["compliance_checks"]
adviser_decisions_col = db["adviser_decisions"]
audit_logs_col = db["audit_logs"]
breach_flags_col = db["breach_flags"]
licensees_col = db["licensees"]
advisers_col = db["advisers"]

# ==================== PDF GENERATION HELPERS ====================

def create_compliance_report_pdf(
    report_data: Dict[str, Any],
    report_type: str
) -> bytes:
    """Generate a PDF compliance report using ReportLab."""
    try:
        from reportlab.lib import colors
        from reportlab.lib.pagesizes import A4
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.lib.units import mm, inch
        from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image, PageBreak
        from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
        
        buffer = io.BytesIO()
        doc = SimpleDocTemplate(
            buffer,
            pagesize=A4,
            rightMargin=20*mm,
            leftMargin=20*mm,
            topMargin=20*mm,
            bottomMargin=20*mm
        )
        
        styles = getSampleStyleSheet()
        
        # Custom styles
        title_style = ParagraphStyle(
            'CustomTitle',
            parent=styles['Heading1'],
            fontSize=24,
            spaceAfter=30,
            textColor=colors.HexColor('#1a1a2e'),
            alignment=TA_CENTER
        )
        
        subtitle_style = ParagraphStyle(
            'CustomSubtitle',
            parent=styles['Heading2'],
            fontSize=16,
            spaceAfter=15,
            textColor=colors.HexColor('#D4A84C')
        )
        
        section_style = ParagraphStyle(
            'SectionHeader',
            parent=styles['Heading3'],
            fontSize=14,
            spaceAfter=10,
            spaceBefore=20,
            textColor=colors.HexColor('#333333')
        )
        
        _body_style = ParagraphStyle(
            'BodyText',
            parent=styles['Normal'],
            fontSize=10,
            spaceAfter=8
        )
        
        small_style = ParagraphStyle(
            'SmallText',
            parent=styles['Normal'],
            fontSize=8,
            textColor=colors.HexColor('#666666')
        )
        
        story = []
        
        # Header
        story.append(Paragraph("WEALTH COMMAND", title_style))
        story.append(Paragraph("AdviceOS Compliance Report", subtitle_style))
        story.append(Spacer(1, 10))
        
        # Report metadata
        generated_at = report_data.get("generated_at", datetime.now(timezone.utc).isoformat())
        meta_data = [
            ["Report Type:", report_type.replace("_", " ").title()],
            ["Generated:", generated_at[:19].replace("T", " ")],
            ["Report ID:", str(uuid.uuid4())[:8].upper()]
        ]
        
        meta_table = Table(meta_data, colWidths=[80, 200])
        meta_table.setStyle(TableStyle([
            ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 10),
            ('TEXTCOLOR', (0, 0), (-1, -1), colors.HexColor('#333333')),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
        ]))
        story.append(meta_table)
        story.append(Spacer(1, 20))
        
        # Compliance Disclaimer
        disclaimer_style = ParagraphStyle(
            'Disclaimer',
            parent=styles['Normal'],
            fontSize=9,
            textColor=colors.HexColor('#666666'),
            backColor=colors.HexColor('#f5f5f5'),
            borderPadding=10
        )
        disclaimer_text = """
        <b>COMPLIANCE NOTICE:</b> This report is generated by Wealth Command AdviceOS for 
        compliance and audit purposes. This tool provides decision support only and does not 
        constitute financial advice. All scenarios are for comparison purposes only. 
        The adviser must confirm all outputs before presenting to clients.
        """
        story.append(Paragraph(disclaimer_text, disclaimer_style))
        story.append(Spacer(1, 20))
        
        # Summary Section
        if "summary" in report_data:
            story.append(Paragraph("Executive Summary", section_style))
            summary = report_data["summary"]
            
            summary_items = []
            if "compliance_score" in summary:
                summary_items.append(["Compliance Score", f"{summary['compliance_score']}%"])
            if "scenarios" in summary:
                summary_items.append(["Total Scenarios", str(summary['scenarios'].get('total', 0))])
            if "decisions" in summary:
                summary_items.append(["Decisions Made", str(summary['decisions'].get('total', 0))])
                summary_items.append(["Overrides", str(summary['decisions'].get('overrides', 0))])
            if "breaches" in summary:
                summary_items.append(["Open Breaches", str(summary['breaches'].get('open', 0))])
            
            if summary_items:
                summary_table = Table(summary_items, colWidths=[150, 150])
                summary_table.setStyle(TableStyle([
                    ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
                    ('FONTSIZE', (0, 0), (-1, -1), 11),
                    ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#dddddd')),
                    ('BACKGROUND', (0, 0), (0, -1), colors.HexColor('#f9f9f9')),
                    ('PADDING', (0, 0), (-1, -1), 8),
                ]))
                story.append(summary_table)
                story.append(Spacer(1, 20))
        
        # Compliance Checks Section
        if "compliance_checks" in report_data:
            story.append(Paragraph("Compliance Check Results", section_style))
            checks = report_data["compliance_checks"]
            
            if isinstance(checks, dict):
                check_data = [
                    ["Passed", str(checks.get("passed", 0))],
                    ["Warnings", str(checks.get("warnings", 0))],
                    ["Blocked", str(checks.get("blocked", 0))],
                    ["Total", str(checks.get("total", 0))]
                ]
                
                check_table = Table(check_data, colWidths=[150, 100])
                check_table.setStyle(TableStyle([
                    ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
                    ('FONTSIZE', (0, 0), (-1, -1), 10),
                    ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#dddddd')),
                    ('BACKGROUND', (0, 0), (0, 0), colors.HexColor('#dcfce7')),  # Green for passed
                    ('BACKGROUND', (0, 1), (0, 1), colors.HexColor('#fef9c3')),  # Yellow for warnings
                    ('BACKGROUND', (0, 2), (0, 2), colors.HexColor('#fee2e2')),  # Red for blocked
                    ('PADDING', (0, 0), (-1, -1), 8),
                ]))
                story.append(check_table)
                story.append(Spacer(1, 20))
        
        # Breaches Section
        if "breaches" in report_data and report_data["breaches"]:
            story.append(Paragraph("Compliance Breaches", section_style))
            breaches = report_data["breaches"]
            
            if isinstance(breaches, list) and breaches:
                breach_headers = ["Severity", "Type", "Status", "Date"]
                breach_data = [breach_headers]
                
                for breach in breaches[:20]:  # Limit to 20
                    breach_data.append([
                        breach.get("severity", "").upper(),
                        breach.get("breach_type", "")[:30],
                        breach.get("status", ""),
                        breach.get("detected_at", "")[:10] if breach.get("detected_at") else ""
                    ])
                
                breach_table = Table(breach_data, colWidths=[70, 180, 80, 80])
                breach_table.setStyle(TableStyle([
                    ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                    ('FONTSIZE', (0, 0), (-1, -1), 9),
                    ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#dddddd')),
                    ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#D4A84C')),
                    ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
                    ('PADDING', (0, 0), (-1, -1), 6),
                    ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
                ]))
                story.append(breach_table)
                story.append(Spacer(1, 20))
        
        # Audit Trail Section
        if "audit_logs" in report_data and report_data["audit_logs"]:
            story.append(PageBreak())
            story.append(Paragraph("Audit Trail", section_style))
            logs = report_data["audit_logs"]
            
            if isinstance(logs, list) and logs:
                log_headers = ["Timestamp", "User", "Action", "Entity"]
                log_data = [log_headers]
                
                for log in logs[:30]:  # Limit to 30
                    log_data.append([
                        log.get("timestamp", "")[:19].replace("T", " ") if log.get("timestamp") else "",
                        log.get("user_id", "")[:15],
                        log.get("action_type", ""),
                        log.get("entity_type", "")
                    ])
                
                log_table = Table(log_data, colWidths=[110, 100, 80, 100])
                log_table.setStyle(TableStyle([
                    ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                    ('FONTSIZE', (0, 0), (-1, -1), 8),
                    ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#dddddd')),
                    ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#333333')),
                    ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
                    ('PADDING', (0, 0), (-1, -1), 4),
                    ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
                ]))
                story.append(log_table)
        
        # Footer
        story.append(Spacer(1, 30))
        footer_text = f"""
        <b>Wealth Command AdviceOS</b><br/>
        Compliance-First Financial Decision Support Platform<br/>
        Report generated: {generated_at[:19].replace("T", " ")} UTC<br/>
        © 2026 Wealth Command - All Rights Reserved
        """
        story.append(Paragraph(footer_text, small_style))
        
        # Build PDF
        doc.build(story)
        buffer.seek(0)
        return buffer.getvalue()
        
    except ImportError as e:
        logger.error(f"ReportLab not available: {e}")
        raise HTTPException(status_code=500, detail="PDF generation library not available")
    except Exception as e:
        logger.error(f"PDF generation error: {e}")
        raise HTTPException(status_code=500, detail=f"PDF generation failed: {str(e)}")

# ==================== API ENDPOINTS ====================

@router.get("/compliance-summary")
async def download_compliance_summary_pdf(
    licensee_id: str = "lic_default",
    start_date: Optional[str] = None,
    end_date: Optional[str] = None
):
    """Generate and download a compliance summary PDF report."""
    query = {}
    if start_date:
        query["created_at"] = {"$gte": start_date}
    if end_date:
        if "created_at" in query:
            query["created_at"]["$lte"] = end_date
        else:
            query["created_at"] = {"$lte": end_date}
    
    # Gather data
    checks = await compliance_checks_col.find(query, {"_id": 0}).to_list(1000)
    breaches = await breach_flags_col.find({}, {"_id": 0}).to_list(100)
    logs = await audit_logs_col.find({}, {"_id": 0}).sort("timestamp", -1).limit(50).to_list(50)
    
    total_checks = len(checks)
    passed = len([c for c in checks if c.get("overall_result") == "pass"])
    warnings = len([c for c in checks if c.get("overall_result") == "warning"])
    blocked = len([c for c in checks if c.get("overall_result") == "block"])
    
    compliance_score = round(passed / max(1, total_checks) * 100, 1) if total_checks > 0 else 100
    
    report_data = {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "summary": {
            "compliance_score": compliance_score,
            "scenarios": {"total": await scenarios_col.count_documents({})},
            "decisions": {
                "total": await adviser_decisions_col.count_documents({}),
                "overrides": await adviser_decisions_col.count_documents({"override_occurred": True})
            },
            "breaches": {
                "open": len([b for b in breaches if b.get("status") == "open"]),
                "total": len(breaches)
            }
        },
        "compliance_checks": {
            "total": total_checks,
            "passed": passed,
            "warnings": warnings,
            "blocked": blocked
        },
        "breaches": breaches,
        "audit_logs": logs
    }
    
    pdf_bytes = create_compliance_report_pdf(report_data, "compliance_summary")
    
    filename = f"compliance_summary_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"
    
    return StreamingResponse(
        io.BytesIO(pdf_bytes),
        media_type="application/pdf",
        headers={"Content-Disposition": f"attachment; filename={filename}"}
    )

@router.get("/audit-trail")
async def download_audit_trail_pdf(
    user_id: Optional[str] = None,
    entity_type: Optional[str] = None,
    limit: int = 100
):
    """Generate and download an audit trail PDF report."""
    query = {}
    if user_id:
        query["user_id"] = user_id
    if entity_type:
        query["entity_type"] = entity_type
    
    logs = await audit_logs_col.find(query, {"_id": 0}).sort("timestamp", -1).limit(limit).to_list(limit)
    
    report_data = {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "audit_logs": logs
    }
    
    pdf_bytes = create_compliance_report_pdf(report_data, "audit_trail")
    
    filename = f"audit_trail_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"
    
    return StreamingResponse(
        io.BytesIO(pdf_bytes),
        media_type="application/pdf",
        headers={"Content-Disposition": f"attachment; filename={filename}"}
    )

@router.get("/breach-report")
async def download_breach_report_pdf(
    status: Optional[str] = None,
    severity: Optional[str] = None
):
    """Generate and download a breach report PDF."""
    query = {}
    if status:
        query["status"] = status
    if severity:
        query["severity"] = severity
    
    breaches = await breach_flags_col.find(query, {"_id": 0}).sort("detected_at", -1).to_list(500)
    
    report_data = {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "summary": {
            "breaches": {
                "open": len([b for b in breaches if b.get("status") == "open"]),
                "total": len(breaches)
            }
        },
        "breaches": breaches
    }
    
    pdf_bytes = create_compliance_report_pdf(report_data, "breach_report")
    
    filename = f"breach_report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"
    
    return StreamingResponse(
        io.BytesIO(pdf_bytes),
        media_type="application/pdf",
        headers={"Content-Disposition": f"attachment; filename={filename}"}
    )

@router.get("/client-file/{client_id}")
async def download_client_file_pdf(client_id: str):
    """Generate and download a complete client file PDF."""
    # Get all scenarios for client
    scenarios = await scenarios_col.find({"client_id": client_id}, {"_id": 0}).to_list(100)
    
    # Get all decisions for client's scenarios
    scenario_ids = [s.get("id") for s in scenarios]
    decisions = await adviser_decisions_col.find(
        {"scenario_set_id": {"$in": scenario_ids}},
        {"_id": 0}
    ).to_list(100)
    
    # Get compliance checks
    checks = await compliance_checks_col.find(
        {"scenario_set_id": {"$in": scenario_ids}},
        {"_id": 0}
    ).to_list(100)
    
    # Get audit trail for client
    logs = await audit_logs_col.find(
        {"entity_id": {"$in": [client_id] + scenario_ids}},
        {"_id": 0}
    ).sort("timestamp", 1).to_list(500)
    
    passed = len([c for c in checks if c.get("overall_result") == "pass"])
    total = len(checks)
    
    report_data = {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "summary": {
            "compliance_score": round(passed / max(1, total) * 100, 1) if total > 0 else 100,
            "scenarios": {"total": len(scenarios)},
            "decisions": {
                "total": len(decisions),
                "overrides": len([d for d in decisions if d.get("override_occurred")])
            }
        },
        "compliance_checks": {
            "total": total,
            "passed": passed,
            "warnings": len([c for c in checks if c.get("overall_result") == "warning"]),
            "blocked": len([c for c in checks if c.get("overall_result") == "block"])
        },
        "audit_logs": logs
    }
    
    pdf_bytes = create_compliance_report_pdf(report_data, f"client_file_{client_id}")
    
    filename = f"client_file_{client_id}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"
    
    return StreamingResponse(
        io.BytesIO(pdf_bytes),
        media_type="application/pdf",
        headers={"Content-Disposition": f"attachment; filename={filename}"}
    )

@router.get("/adviser-activity/{adviser_id}")
async def download_adviser_activity_pdf(adviser_id: str):
    """Generate and download an adviser activity PDF report."""
    # Get scenarios by adviser
    scenarios = await scenarios_col.find({"adviser_id": adviser_id}, {"_id": 0}).to_list(100)
    
    # Get decisions by adviser
    decisions = await adviser_decisions_col.find({"adviser_id": adviser_id}, {"_id": 0}).to_list(100)
    
    # Get audit logs for adviser
    logs = await audit_logs_col.find({"user_id": adviser_id}, {"_id": 0}).sort("timestamp", -1).limit(100).to_list(100)
    
    report_data = {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "summary": {
            "scenarios": {"total": len(scenarios)},
            "decisions": {
                "total": len(decisions),
                "overrides": len([d for d in decisions if d.get("override_occurred")])
            }
        },
        "audit_logs": logs
    }
    
    pdf_bytes = create_compliance_report_pdf(report_data, f"adviser_activity_{adviser_id}")
    
    filename = f"adviser_activity_{adviser_id}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"
    
    return StreamingResponse(
        io.BytesIO(pdf_bytes),
        media_type="application/pdf",
        headers={"Content-Disposition": f"attachment; filename={filename}"}
    )
