import { createContext, useContext, useState, useCallback } from 'react';

const translations = {
  en: {
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.myDashboard': 'My Dashboard',
    'nav.markets': 'Markets',
    'nav.planning': 'Planning',
    'nav.investments': 'Investments',
    'nav.netWorth': 'Net Worth',
    'nav.sharesEtfs': 'Shares & ETFs',
    'nav.bonds': 'Bonds',
    'nav.hybrids': 'Hybrids',
    'nav.property': 'Property',
    'nav.unlisted': 'Unlisted',
    'nav.cashTds': 'Cash & TDs',
    'nav.managedFunds': 'Managed Funds',
    'nav.crypto': 'Crypto',
    'nav.superPension': 'Super & Pension',
    'nav.tools': 'Tools',
    'nav.settings': 'Settings',
    // Common
    'common.search': 'Search...',
    'common.refresh': 'Refresh',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.close': 'Close',
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.download': 'Download',
    'common.export': 'Export',
    'common.submit': 'Submit',
    'common.generate': 'Generate',
    'common.viewDetails': 'View Details',
    'common.noData': 'No data available',
    'common.demoMode': 'Demo Mode',
    // Voice Assistant
    'voice.title': 'Financial Planning Assistant',
    'voice.subtitle': 'Ask me anything about your finances',
    'voice.placeholder': 'Type your question or click the mic...',
    'voice.recording': 'Listening...',
    'voice.processing': 'Processing...',
    'voice.disclaimer': 'General advice only. Consult a licensed financial adviser for personal advice.',
    // Stock Trading
    'stocks.title': 'Shares & ETFs',
    'stocks.subtitle': 'Trade, analyze, and optimize your equity portfolio',
    'stocks.portfolio': 'Portfolio',
    'stocks.buffettIdeas': 'Buffett Ideas',
    'stocks.valuations': 'Valuations',
    'stocks.backtest': 'Backtest',
    'stocks.news': 'News',
    'stocks.liveMarkets': 'Live Markets',
    'stocks.portfolioValue': 'Portfolio Value',
    'stocks.costBase': 'Cost Base',
    'stocks.unrealizedGain': 'Unrealized Gain/Loss',
    'stocks.buy': 'Buy',
    'stocks.sell': 'Sell',
    'stocks.executeOrder': 'Execute Order',
    'stocks.orderValue': 'Order Value',
    'stocks.confidence': 'Confidence',
    'stocks.sentiment': 'Market Sentiment',
    'stocks.sectorRankings': 'Sector Rankings',
    // AdviceOS
    'adviceos.title': 'AdviceOS',
    'adviceos.subtitle': 'Compliance-First Decision Support Platform',
    'adviceos.disclaimer': 'This tool provides decision support only',
    'adviceos.disclaimerDetail': 'This is not financial advice. All scenarios are for comparison purposes only.',
    'adviceos.complianceScore': 'Compliance Score',
    'adviceos.scenarios': 'Scenarios',
    'adviceos.decisions': 'Decisions',
    'adviceos.openBreaches': 'Open Breaches',
    'adviceos.auditEntries': 'Audit Entries',
    'adviceos.overview': 'Overview',
    'adviceos.compliance': 'Compliance',
    'adviceos.auditTrail': 'Audit Trail',
    'adviceos.reports': 'Reports',
    'adviceos.generateScenarios': 'Generate Scenarios',
    'adviceos.passedChecks': 'Passed Checks',
    'adviceos.warnings': 'Warnings',
    'adviceos.blocked': 'Blocked',
    'adviceos.recentActivity': 'Recent Activity',
    'adviceos.recordDecision': 'Record Adviser Decision',
    'adviceos.justification': 'Justification',
    // Retirement
    'retirement.title': 'Retirement Confidence',
    'retirement.subtitle': 'Monte Carlo simulation and confidence scoring',
    'retirement.confidenceScore': 'Confidence Score',
    'retirement.scenarioImpact': 'Scenario Impact',
    'retirement.positionSummary': 'Position Summary',
    'retirement.confidenceDrivers': 'Confidence Drivers',
    'retirement.monteCarloResults': 'Monte Carlo Results',
    'retirement.surplus': 'Surplus',
    'retirement.shortfall': 'Shortfall',
    'retirement.runSimulation': 'Run Simulation',
    // Strategic Planning
    'planning.title': 'Strategic Financial Planning',
    'planning.subtitle': 'Comprehensive wealth projection and scenario analysis',
    'planning.netWorthProjection': 'Net Worth Projection',
    'planning.goalTracker': 'Goal Tracker',
    'planning.estatePlanning': 'Estate Planning',
    'planning.scenarioComparison': 'Scenario Comparison',
    'planning.addScenario': 'Add Scenario',
    'planning.analyze': 'Analyze',
    // Compliance
    'compliance.title': 'Adviser Compliance Dashboard',
    'compliance.subtitle': 'Monitor advice quality, ASIC compliance, and regulatory alignment',
    'compliance.breaches': 'Compliance Breaches',
    'compliance.noBreaches': 'No compliance breaches recorded',
    // Language
    'lang.english': 'English',
    'lang.mandarin': '中文',
    'lang.vietnamese': 'Tiếng Việt',
    'lang.greek': 'Ελληνικά',
  },
  zh: {
    'nav.dashboard': '仪表板',
    'nav.myDashboard': '我的仪表板',
    'nav.markets': '市场',
    'nav.planning': '规划',
    'nav.investments': '投资',
    'nav.netWorth': '净资产',
    'nav.sharesEtfs': '股票和ETF',
    'nav.bonds': '债券',
    'nav.hybrids': '混合型',
    'nav.property': '房产',
    'nav.unlisted': '非上市',
    'nav.cashTds': '现金和定期存款',
    'nav.managedFunds': '管理基金',
    'nav.crypto': '加密货币',
    'nav.superPension': '养老金',
    'nav.tools': '工具',
    'nav.settings': '设置',
    'common.search': '搜索...',
    'common.refresh': '刷新',
    'common.save': '保存',
    'common.cancel': '取消',
    'common.close': '关闭',
    'common.loading': '加载中...',
    'common.error': '错误',
    'common.success': '成功',
    'common.download': '下载',
    'common.export': '导出',
    'common.submit': '提交',
    'common.generate': '生成',
    'common.viewDetails': '查看详情',
    'common.noData': '暂无数据',
    'common.demoMode': '演示模式',
    'voice.title': '财务规划助手',
    'voice.subtitle': '询问有关您财务的任何问题',
    'voice.placeholder': '输入您的问题或点击麦克风...',
    'voice.recording': '正在聆听...',
    'voice.processing': '处理中...',
    'voice.disclaimer': '仅供一般建议。请咨询持牌财务顾问获取个人建议。',
    'stocks.title': '股票和ETF',
    'stocks.subtitle': '交易、分析和优化您的股票投资组合',
    'stocks.portfolio': '投资组合',
    'stocks.buffettIdeas': '巴菲特理念',
    'stocks.valuations': '估值',
    'stocks.backtest': '回测',
    'stocks.news': '新闻',
    'stocks.liveMarkets': '实时市场',
    'stocks.portfolioValue': '投资组合价值',
    'stocks.costBase': '成本基础',
    'stocks.unrealizedGain': '未实现盈亏',
    'stocks.buy': '买入',
    'stocks.sell': '卖出',
    'stocks.executeOrder': '执行订单',
    'stocks.orderValue': '订单金额',
    'stocks.confidence': '信心指数',
    'stocks.sentiment': '市场情绪',
    'stocks.sectorRankings': '板块排名',
    'adviceos.title': 'AdviceOS',
    'adviceos.subtitle': '合规优先决策支持平台',
    'adviceos.disclaimer': '此工具仅提供决策支持',
    'adviceos.disclaimerDetail': '这不是财务建议。所有方案仅供比较。',
    'adviceos.complianceScore': '合规评分',
    'adviceos.scenarios': '情景',
    'adviceos.decisions': '决策',
    'adviceos.openBreaches': '未解决违规',
    'adviceos.auditEntries': '审计记录',
    'adviceos.overview': '概览',
    'adviceos.compliance': '合规',
    'adviceos.auditTrail': '审计跟踪',
    'adviceos.reports': '报告',
    'adviceos.generateScenarios': '生成情景',
    'adviceos.passedChecks': '通过检查',
    'adviceos.warnings': '警告',
    'adviceos.blocked': '已阻止',
    'adviceos.recentActivity': '最近活动',
    'adviceos.recordDecision': '记录顾问决策',
    'adviceos.justification': '理由',
    'retirement.title': '退休信心',
    'retirement.subtitle': '蒙特卡罗模拟和信心评分',
    'retirement.confidenceScore': '信心评分',
    'retirement.scenarioImpact': '情景影响',
    'retirement.positionSummary': '现状摘要',
    'retirement.confidenceDrivers': '信心驱动因素',
    'retirement.monteCarloResults': '蒙特卡罗结果',
    'retirement.surplus': '盈余',
    'retirement.shortfall': '缺口',
    'retirement.runSimulation': '运行模拟',
    'planning.title': '战略财务规划',
    'planning.subtitle': '综合财富预测和情景分析',
    'planning.netWorthProjection': '净资产预测',
    'planning.goalTracker': '目标跟踪',
    'planning.estatePlanning': '遗产规划',
    'planning.scenarioComparison': '情景比较',
    'planning.addScenario': '添加情景',
    'planning.analyze': '分析',
    'compliance.title': '顾问合规仪表板',
    'compliance.subtitle': '监控建议质量、ASIC合规性和监管一致性',
    'compliance.breaches': '合规违规',
    'compliance.noBreaches': '无合规违规记录',
    'lang.english': 'English',
    'lang.mandarin': '中文',
    'lang.vietnamese': 'Tiếng Việt',
    'lang.greek': 'Ελληνικά',
  },
  vi: {
    'nav.dashboard': 'Bảng điều khiển',
    'nav.myDashboard': 'Bảng điều khiển của tôi',
    'nav.markets': 'Thị trường',
    'nav.planning': 'Kế hoạch',
    'nav.investments': 'Đầu tư',
    'nav.netWorth': 'Giá trị ròng',
    'nav.sharesEtfs': 'Cổ phiếu & ETF',
    'nav.bonds': 'Trái phiếu',
    'nav.hybrids': 'Kết hợp',
    'nav.property': 'Bất động sản',
    'nav.unlisted': 'Chưa niêm yết',
    'nav.cashTds': 'Tiền mặt & Tiền gửi',
    'nav.managedFunds': 'Quỹ quản lý',
    'nav.crypto': 'Tiền điện tử',
    'nav.superPension': 'Hưu trí',
    'nav.tools': 'Công cụ',
    'nav.settings': 'Cài đặt',
    'common.search': 'Tìm kiếm...',
    'common.refresh': 'Làm mới',
    'common.save': 'Lưu',
    'common.cancel': 'Hủy',
    'common.close': 'Đóng',
    'common.loading': 'Đang tải...',
    'common.error': 'Lỗi',
    'common.success': 'Thành công',
    'common.download': 'Tải xuống',
    'common.export': 'Xuất',
    'common.submit': 'Gửi',
    'common.generate': 'Tạo',
    'common.viewDetails': 'Xem chi tiết',
    'common.noData': 'Không có dữ liệu',
    'common.demoMode': 'Chế độ demo',
    'voice.title': 'Trợ lý Kế hoạch Tài chính',
    'voice.subtitle': 'Hỏi bất cứ điều gì về tài chính của bạn',
    'voice.placeholder': 'Nhập câu hỏi hoặc nhấn micro...',
    'voice.recording': 'Đang nghe...',
    'voice.processing': 'Đang xử lý...',
    'voice.disclaimer': 'Chỉ tư vấn chung. Hãy tham khảo cố vấn tài chính được cấp phép.',
    'stocks.title': 'Cổ phiếu & ETF',
    'stocks.subtitle': 'Giao dịch, phân tích và tối ưu hóa danh mục cổ phiếu',
    'stocks.portfolio': 'Danh mục',
    'stocks.buffettIdeas': 'Ý tưởng Buffett',
    'stocks.valuations': 'Định giá',
    'stocks.backtest': 'Kiểm tra lịch sử',
    'stocks.news': 'Tin tức',
    'stocks.liveMarkets': 'Thị trường trực tiếp',
    'stocks.portfolioValue': 'Giá trị danh mục',
    'stocks.costBase': 'Giá vốn',
    'stocks.unrealizedGain': 'Lãi/lỗ chưa thực hiện',
    'stocks.buy': 'Mua',
    'stocks.sell': 'Bán',
    'stocks.executeOrder': 'Thực hiện lệnh',
    'stocks.orderValue': 'Giá trị lệnh',
    'stocks.confidence': 'Độ tin cậy',
    'stocks.sentiment': 'Tâm lý thị trường',
    'stocks.sectorRankings': 'Xếp hạng ngành',
    'adviceos.title': 'AdviceOS',
    'adviceos.subtitle': 'Nền tảng hỗ trợ quyết định ưu tiên tuân thủ',
    'adviceos.disclaimer': 'Công cụ này chỉ hỗ trợ quyết định',
    'adviceos.disclaimerDetail': 'Đây không phải tư vấn tài chính. Mọi kịch bản chỉ để so sánh.',
    'adviceos.complianceScore': 'Điểm tuân thủ',
    'adviceos.scenarios': 'Kịch bản',
    'adviceos.decisions': 'Quyết định',
    'adviceos.openBreaches': 'Vi phạm mở',
    'adviceos.auditEntries': 'Bản ghi kiểm toán',
    'adviceos.overview': 'Tổng quan',
    'adviceos.compliance': 'Tuân thủ',
    'adviceos.auditTrail': 'Nhật ký kiểm toán',
    'adviceos.reports': 'Báo cáo',
    'adviceos.generateScenarios': 'Tạo kịch bản',
    'adviceos.passedChecks': 'Đã đạt',
    'adviceos.warnings': 'Cảnh báo',
    'adviceos.blocked': 'Bị chặn',
    'adviceos.recentActivity': 'Hoạt động gần đây',
    'adviceos.recordDecision': 'Ghi nhận quyết định cố vấn',
    'adviceos.justification': 'Lý do',
    'retirement.title': 'Tin tưởng hưu trí',
    'retirement.subtitle': 'Mô phỏng Monte Carlo và chấm điểm tin tưởng',
    'retirement.confidenceScore': 'Điểm tin tưởng',
    'retirement.scenarioImpact': 'Tác động kịch bản',
    'retirement.positionSummary': 'Tóm tắt tình hình',
    'retirement.confidenceDrivers': 'Yếu tố ảnh hưởng',
    'retirement.monteCarloResults': 'Kết quả Monte Carlo',
    'retirement.surplus': 'Thặng dư',
    'retirement.shortfall': 'Thiếu hụt',
    'retirement.runSimulation': 'Chạy mô phỏng',
    'planning.title': 'Kế hoạch tài chính chiến lược',
    'planning.subtitle': 'Dự báo tài sản toàn diện và phân tích kịch bản',
    'planning.netWorthProjection': 'Dự báo giá trị ròng',
    'planning.goalTracker': 'Theo dõi mục tiêu',
    'planning.estatePlanning': 'Kế hoạch thừa kế',
    'planning.scenarioComparison': 'So sánh kịch bản',
    'planning.addScenario': 'Thêm kịch bản',
    'planning.analyze': 'Phân tích',
    'compliance.title': 'Bảng Tuân thủ Cố vấn',
    'compliance.subtitle': 'Giám sát chất lượng tư vấn, tuân thủ ASIC và phù hợp quy định',
    'compliance.breaches': 'Vi phạm tuân thủ',
    'compliance.noBreaches': 'Không có vi phạm tuân thủ',
    'lang.english': 'English',
    'lang.mandarin': '中文',
    'lang.vietnamese': 'Tiếng Việt',
    'lang.greek': 'Ελληνικά',
  },
  el: {
    'nav.dashboard': 'Πίνακας ελέγχου',
    'nav.myDashboard': 'Ο πίνακάς μου',
    'nav.markets': 'Αγορές',
    'nav.planning': 'Σχεδιασμός',
    'nav.investments': 'Επενδύσεις',
    'nav.netWorth': 'Καθαρή αξία',
    'nav.sharesEtfs': 'Μετοχές & ETF',
    'nav.bonds': 'Ομόλογα',
    'nav.hybrids': 'Υβριδικά',
    'nav.property': 'Ακίνητα',
    'nav.unlisted': 'Μη εισηγμένα',
    'nav.cashTds': 'Μετρητά & Προθεσμιακές',
    'nav.managedFunds': 'Διαχειριζόμενα κεφάλαια',
    'nav.crypto': 'Κρυπτονομίσματα',
    'nav.superPension': 'Σύνταξη',
    'nav.tools': 'Εργαλεία',
    'nav.settings': 'Ρυθμίσεις',
    'common.search': 'Αναζήτηση...',
    'common.refresh': 'Ανανέωση',
    'common.save': 'Αποθήκευση',
    'common.cancel': 'Ακύρωση',
    'common.close': 'Κλείσιμο',
    'common.loading': 'Φόρτωση...',
    'common.error': 'Σφάλμα',
    'common.success': 'Επιτυχία',
    'common.download': 'Λήψη',
    'common.export': 'Εξαγωγή',
    'common.submit': 'Υποβολή',
    'common.generate': 'Δημιουργία',
    'common.viewDetails': 'Προβολή λεπτομερειών',
    'common.noData': 'Δεν υπάρχουν δεδομένα',
    'common.demoMode': 'Λειτουργία επίδειξης',
    'voice.title': 'Βοηθός Οικονομικού Σχεδιασμού',
    'voice.subtitle': 'Ρωτήστε οτιδήποτε για τα οικονομικά σας',
    'voice.placeholder': 'Πληκτρολογήστε την ερώτησή σας ή πατήστε το μικρόφωνο...',
    'voice.recording': 'Ακούω...',
    'voice.processing': 'Επεξεργασία...',
    'voice.disclaimer': 'Μόνο γενικές συμβουλές. Συμβουλευτείτε αδειοδοτημένο σύμβουλο.',
    'stocks.title': 'Μετοχές & ETF',
    'stocks.subtitle': 'Συναλλαγές, ανάλυση και βελτιστοποίηση του χαρτοφυλακίου',
    'stocks.portfolio': 'Χαρτοφυλάκιο',
    'stocks.buffettIdeas': 'Ιδέες Buffett',
    'stocks.valuations': 'Αποτιμήσεις',
    'stocks.backtest': 'Ιστορικός έλεγχος',
    'stocks.news': 'Νέα',
    'stocks.liveMarkets': 'Ζωντανές αγορές',
    'stocks.portfolioValue': 'Αξία χαρτοφυλακίου',
    'stocks.costBase': 'Βάση κόστους',
    'stocks.unrealizedGain': 'Μη πραγματοποιημένο κέρδος/ζημία',
    'stocks.buy': 'Αγορά',
    'stocks.sell': 'Πώληση',
    'stocks.executeOrder': 'Εκτέλεση εντολής',
    'stocks.orderValue': 'Αξία εντολής',
    'stocks.confidence': 'Εμπιστοσύνη',
    'stocks.sentiment': 'Αίσθηση αγοράς',
    'stocks.sectorRankings': 'Κατάταξη τομέων',
    'adviceos.title': 'AdviceOS',
    'adviceos.subtitle': 'Πλατφόρμα υποστήριξης αποφάσεων με προτεραιότητα συμμόρφωσης',
    'adviceos.disclaimer': 'Αυτό το εργαλείο παρέχει μόνο υποστήριξη αποφάσεων',
    'adviceos.disclaimerDetail': 'Δεν αποτελεί οικονομική συμβουλή. Τα σενάρια είναι μόνο για σύγκριση.',
    'adviceos.complianceScore': 'Βαθμολογία συμμόρφωσης',
    'adviceos.scenarios': 'Σενάρια',
    'adviceos.decisions': 'Αποφάσεις',
    'adviceos.openBreaches': 'Ανοιχτές παραβιάσεις',
    'adviceos.auditEntries': 'Εγγραφές ελέγχου',
    'adviceos.overview': 'Επισκόπηση',
    'adviceos.compliance': 'Συμμόρφωση',
    'adviceos.auditTrail': 'Ίχνος ελέγχου',
    'adviceos.reports': 'Αναφορές',
    'adviceos.generateScenarios': 'Δημιουργία σεναρίων',
    'adviceos.passedChecks': 'Επιτυχείς έλεγχοι',
    'adviceos.warnings': 'Προειδοποιήσεις',
    'adviceos.blocked': 'Αποκλεισμένα',
    'adviceos.recentActivity': 'Πρόσφατη δραστηριότητα',
    'adviceos.recordDecision': 'Καταγραφή απόφασης συμβούλου',
    'adviceos.justification': 'Αιτιολόγηση',
    'retirement.title': 'Εμπιστοσύνη συνταξιοδότησης',
    'retirement.subtitle': 'Προσομοίωση Monte Carlo και βαθμολογία εμπιστοσύνης',
    'retirement.confidenceScore': 'Βαθμολογία εμπιστοσύνης',
    'retirement.scenarioImpact': 'Επίπτωση σεναρίου',
    'retirement.positionSummary': 'Σύνοψη θέσης',
    'retirement.confidenceDrivers': 'Παράγοντες εμπιστοσύνης',
    'retirement.monteCarloResults': 'Αποτελέσματα Monte Carlo',
    'retirement.surplus': 'Πλεόνασμα',
    'retirement.shortfall': 'Έλλειμμα',
    'retirement.runSimulation': 'Εκτέλεση προσομοίωσης',
    'planning.title': 'Στρατηγικός οικονομικός σχεδιασμός',
    'planning.subtitle': 'Ολοκληρωμένη πρόβλεψη πλούτου και ανάλυση σεναρίων',
    'planning.netWorthProjection': 'Πρόβλεψη καθαρής αξίας',
    'planning.goalTracker': 'Παρακολούθηση στόχων',
    'planning.estatePlanning': 'Σχεδιασμός κληρονομιάς',
    'planning.scenarioComparison': 'Σύγκριση σεναρίων',
    'planning.addScenario': 'Προσθήκη σεναρίου',
    'planning.analyze': 'Ανάλυση',
    'compliance.title': 'Πίνακας Συμμόρφωσης Συμβούλου',
    'compliance.subtitle': 'Παρακολούθηση ποιότητας συμβουλών, συμμόρφωση ASIC',
    'compliance.breaches': 'Παραβιάσεις συμμόρφωσης',
    'compliance.noBreaches': 'Δεν υπάρχουν παραβιάσεις',
    'lang.english': 'English',
    'lang.mandarin': '中文',
    'lang.vietnamese': 'Tiếng Việt',
    'lang.greek': 'Ελληνικά',
  },
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    if (typeof window !== 'undefined') {
      return localStorage.getItem('halcyon_language') || 'en';
    }
    return 'en';
  });

  const changeLanguage = useCallback((lang) => {
    setLanguage(lang);
    localStorage.setItem('halcyon_language', lang);
  }, []);

  const t = useCallback((key) => {
    return translations[language]?.[key] || translations.en[key] || key;
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, changeLanguage, t, availableLanguages: Object.keys(translations) }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    return { language: 'en', changeLanguage: () => {}, t: (key) => key, availableLanguages: ['en'] };
  }
  return context;
};

export const LANGUAGE_LABELS = {
  en: 'English',
  zh: '中文 (Mandarin)',
  vi: 'Tiếng Việt',
  el: 'Ελληνικά (Greek)',
};

export default LanguageContext;
