// Client360 view — constants & demo seed data
// Split out of Client360View.jsx for maintainability. Pure data, no JSX.
import {
  TrendingUp,
  DollarSign,
  Target,
  Briefcase,
  Building2,
  Home,
  PiggyBank,
  Shield,
  Bitcoin,
  Coins,
  Landmark,
  GraduationCap,
} from "lucide-react";

export const PERFORMANCE_TIMEFRAMES = ["1M", "3M", "6M", "1Y", "2Y", "3Y", "5Y", "10Y"];

export const ASSET_ICONS = {
  Super: PiggyBank,
  Property: Home,
  Shares: TrendingUp,
  "Managed Fund": TrendingUp,
  Cash: DollarSign,
  Crypto: TrendingUp,
  Other: Building2,
};

export const CLIENT_ID_MAP = {
  client_1: "thompson_family",
  client_2: "chen_family",
  thompson_family: "thompson_family",
  chen_family: "chen_family",
};

// Detailed asset holdings by category (mock demo data for Holdings tab)
export const ASSET_HOLDINGS = {
  stocks: {
    label: "Stocks & ETFs",
    icon: TrendingUp,
    color: "#3B82F6",
    total: 425000,
    holdings: [
      { name: "BHP Group", symbol: "BHP", units: 1200, price: 45.50, value: 54600, change: 5.2, costBase: 48000 },
      { name: "Commonwealth Bank", symbol: "CBA", units: 400, price: 118.50, value: 47400, change: 8.1, costBase: 42000 },
      { name: "CSL Limited", symbol: "CSL", units: 150, price: 295.00, value: 44250, change: -2.3, costBase: 46000 },
      { name: "Vanguard Aus Shares (VAS)", symbol: "VAS", units: 1500, price: 95.50, value: 143250, change: 4.5, costBase: 135000 },
      { name: "iShares S&P 500 (IVV)", symbol: "IVV", units: 120, price: 580.00, value: 69600, change: 12.4, costBase: 58000 },
      { name: "Vanguard Intl (VGS)", symbol: "VGS", units: 450, price: 115.00, value: 51750, change: 9.8, costBase: 45000 },
      { name: "Magellan Global (MGE)", symbol: "MGE", units: 350, price: 42.00, value: 14700, change: -5.2, costBase: 16500 },
    ],
    research: [
      { title: "BHP Group - Mining Outlook 2026", date: "2025-12-10", source: "Macquarie Research", rating: "Outperform", target: 52.00 },
      { title: "Australian Banks Sector Update", date: "2025-12-05", source: "Morgan Stanley", rating: "Equal Weight", target: null },
      { title: "VAS ETF Analysis Q4 2025", date: "2025-11-28", source: "Morningstar", rating: "Gold", target: null },
    ],
  },
  bonds: {
    label: "Bonds & Fixed Income",
    icon: Landmark,
    color: "#F59E0B",
    total: 95000,
    holdings: [
      { name: "Aus Gov 10Y Bond", symbol: "ACGB-34", units: 50000, price: 1.02, value: 51000, yield: 4.2, maturity: "2034-03-15" },
      { name: "Corporate Bond Fund", symbol: "BOND", units: 30000, price: 1.05, value: 31500, yield: 5.1, maturity: "2028-06-30" },
      { name: "NSW Treasury Bond", symbol: "NSWTC", units: 12000, price: 1.04, value: 12480, yield: 4.5, maturity: "2030-11-20" },
    ],
    research: [
      { title: "Fixed Income Strategy 2026", date: "2025-12-08", source: "UBS", rating: "Overweight", target: null },
      { title: "Corporate Credit Outlook", date: "2025-11-15", source: "JP Morgan", rating: "Neutral", target: null },
    ],
  },
  hybrids: {
    label: "Hybrid Securities",
    icon: Coins,
    color: "#EC4899",
    total: 85000,
    holdings: [
      { name: "CBA PERLS XI", symbol: "CBAPD", units: 300, price: 98.50, value: 29550, yield: 7.35, maturity: "2026-10-15", franking: 100 },
      { name: "Westpac Capital Notes 8", symbol: "WBCPI", units: 200, price: 101.20, value: 20240, yield: 7.25, maturity: "2027-03-22", franking: 100 },
      { name: "ANZ Capital Notes 7", symbol: "ANZPJ", units: 250, price: 97.80, value: 24450, yield: 7.45, maturity: "2028-09-20", franking: 100 },
      { name: "NAB Capital Notes 5", symbol: "NABPH", units: 110, price: 99.00, value: 10890, yield: 7.30, maturity: "2028-06-17", franking: 100 },
    ],
    research: [
      { title: "Bank Hybrids Market Update", date: "2025-12-12", source: "Bell Potter", rating: "Attractive", target: null },
      { title: "AT1 Capital Notes Analysis", date: "2025-11-28", source: "Citi Research", rating: "Hold", target: null },
    ],
  },
  cash: {
    label: "Cash & Term Deposits",
    icon: PiggyBank,
    color: "#10B981",
    total: 185000,
    holdings: [
      { name: "High Interest Savings", symbol: "ING", units: 1, price: 85000, value: 85000, rate: 5.0, maturity: null },
      { name: "Term Deposit 6M", symbol: "CBA-TD", units: 1, price: 50000, value: 50000, rate: 4.8, maturity: "2026-06-15" },
      { name: "Term Deposit 12M", symbol: "WBC-TD", units: 1, price: 25000, value: 25000, rate: 5.1, maturity: "2026-12-01" },
      { name: "Offset Account", symbol: "CBA-OFF", units: 1, price: 25000, value: 25000, rate: 0, maturity: null },
    ],
    research: [
      { title: "Term Deposit Rate Comparison", date: "2025-12-12", source: "RateCity", rating: "Best Value", target: null },
    ],
  },
  funds: {
    label: "Managed Funds",
    icon: Briefcase,
    color: "#8B5CF6",
    total: 175000,
    holdings: [
      { name: "Magellan Global Fund", symbol: "MGF", units: 3500, price: 32.80, value: 114800, change: -3.2, manager: "Magellan" },
      { name: "Platinum International Fund", symbol: "PIF", units: 2500, price: 24.50, value: 61250, change: 2.8, manager: "Platinum" },
    ],
    research: [
      { title: "Magellan Global Fund Review", date: "2025-12-01", source: "Morningstar", rating: "Silver", target: null },
      { title: "Platinum Intl Fund Analysis", date: "2025-11-20", source: "Lonsec", rating: "Recommended", target: null },
    ],
  },
  crypto: {
    label: "Cryptocurrency",
    icon: Bitcoin,
    color: "#F97316",
    total: 45000,
    holdings: [
      { name: "Bitcoin", symbol: "BTC", units: 0.42, price: 73500, value: 30870, change: 15.2, costBase: 22000 },
      { name: "Ethereum", symbol: "ETH", units: 3.8, price: 3720, value: 14136, change: 8.5, costBase: 10000 },
    ],
    research: [
      { title: "Bitcoin Institutional Outlook 2026", date: "2025-12-14", source: "Fidelity Digital", rating: "Positive", target: 100000 },
    ],
  },
  property: {
    label: "Property",
    icon: Home,
    color: "#EF4444",
    total: 3050000,
    holdings: [
      { name: "Family Home - Mosman", symbol: "PROP-1", units: 1, price: 2200000, value: 2200000, change: 5.3, debt: 850000, rental: 0 },
      { name: "Investment Unit - Parramatta", symbol: "PROP-2", units: 1, price: 850000, value: 850000, change: 3.0, debt: 0, rental: 2800 },
    ],
    research: [
      { title: "Sydney Property Market Update", date: "2025-12-10", source: "CoreLogic", rating: "Moderate Growth", target: null },
      { title: "Parramatta Growth Corridor", date: "2025-11-25", source: "Domain Research", rating: "High Potential", target: null },
    ],
  },
};

// Comprehensive demo client data (per-client dashboards)
export const DEMO_CLIENT_DATA = {
  client_1: {
    id: "client_1",
    name: "David & Sarah Thompson",
    email: "david.thompson@email.com",
    phone: "0412 345 678",
    mobile: "0412 345 678",
    address: "18 Elm Street, Glen Waverley VIC 3150",
    status: "active",
    type: "household",
    clientSince: "2019-03-15",
    dateOfBirth: "1976-03-15",
    age: 50,
    occupation: "IT Manager",
    employer: "NAB",
    riskProfile: "Balanced",
    investmentExperience: "Moderate",
    advisor: "Sarah Chen",
    reviewFrequency: "Annual",
    lastReview: "2025-06-15",
    nextReview: "2026-05-15",
    satisfaction: 92,
    nps: 9,
    wealth: { total: 1608800, change: 87000, changePercent: 5.7, assetAllocation: { equities: 4, property: 70, super: 19, cash: 3, other: 4 } },
    accounts: [
      { id: 1, name: "David - AustralianSuper", type: "Superannuation", institution: "AustralianSuper", balance: 245000, change: 18500, changePercent: 8.2, icon: PiggyBank },
      { id: 2, name: "Sarah - REST Super", type: "Superannuation", institution: "REST", balance: 198000, change: 14300, changePercent: 7.8, icon: PiggyBank },
      { id: 3, name: "Family Home - Glen Waverley", type: "Property", institution: "Direct", balance: 985000, change: 38500, changePercent: 4.1, icon: Home },
      { id: 4, name: "Investment Unit - Brunswick", type: "Property", institution: "Direct", balance: 620000, change: 22600, changePercent: 3.8, icon: Home },
      { id: 5, name: "Vanguard High Growth ETF", type: "Investment", institution: "Vanguard", balance: 42000, change: 3600, changePercent: 9.5, icon: TrendingUp },
      { id: 6, name: "BHP & CBA Shares", type: "Investment", institution: "CommSec", balance: 42500, change: 3400, changePercent: 8.7, icon: TrendingUp },
      { id: 7, name: "Colonial First State Balanced", type: "Managed Fund", institution: "CFS", balance: 32000, change: 1750, changePercent: 5.8, icon: TrendingUp },
      { id: 8, name: "Emergency Fund - ING", type: "Cash", institution: "ING", balance: 28000, change: 1150, changePercent: 4.3, icon: DollarSign },
      { id: 9, name: "Term Deposit - Westpac", type: "Cash", institution: "Westpac", balance: 35000, change: 1540, changePercent: 4.6, icon: DollarSign },
      { id: 10, name: "Home Loan - CBA", type: "Liability", institution: "CBA", balance: -285000, change: 15000, changePercent: 5.0, icon: Building2 },
      { id: 11, name: "Investment Loan - ANZ", type: "Liability", institution: "ANZ", balance: -380000, change: 12000, changePercent: 3.1, icon: Building2 },
      { id: 12, name: "Credit Card - Visa", type: "Liability", institution: "CBA", balance: -4200, change: 800, changePercent: 16.0, icon: Building2 },
    ],
    transactions: [
      { id: 1, date: "2025-12-14", description: "Dividend - BHP Group", amount: 620, type: "income", account: "BHP & CBA Shares" },
      { id: 2, date: "2025-12-12", description: "DRP Reinvestment - CBA", amount: 480, type: "investment", account: "BHP & CBA Shares" },
      { id: 3, date: "2025-12-10", description: "Salary Sacrifice", amount: 1750, type: "contribution", account: "David - AustralianSuper" },
      { id: 4, date: "2025-12-08", description: "Rental Income - Brunswick", amount: 2667, type: "income", account: "Emergency Fund - ING" },
      { id: 5, date: "2025-12-05", description: "Home Loan Payment", amount: -2800, type: "expense", account: "Home Loan - CBA" },
      { id: 6, date: "2025-12-01", description: "Interest Earned", amount: 135, type: "income", account: "Term Deposit - Westpac" },
    ],
    tasks: [
      { id: 1, title: "Super Consolidation Review", priority: "high", dueDate: "2026-02-28", status: "pending", type: "review" },
      { id: 2, title: "Insurance Gap Analysis", priority: "medium", dueDate: "2026-03-15", status: "pending", type: "planning" },
      { id: 3, title: "Annual SOA Update", priority: "medium", dueDate: "2026-05-15", status: "pending", type: "document" },
    ],
    documents: [
      { id: 1, name: "Statement of Advice 2025", type: "SOA", date: "2025-06-15", status: "signed" },
      { id: 2, name: "Fee Disclosure Statement", type: "FDS", date: "2025-12-01", status: "pending_signature" },
      { id: 3, name: "Q3 2025 Portfolio Report", type: "Report", date: "2025-10-01", status: "available" },
    ],
    communications: [
      { id: 1, date: "2025-12-14", type: "email", direction: "outbound", summary: "Sent quarterly portfolio report", by: "Sarah Chen" },
      { id: 2, date: "2025-12-05", type: "call", direction: "inbound", summary: "David asked about super contribution limits", duration: "15 min", by: "David Thompson" },
      { id: 3, date: "2025-11-28", type: "meeting", direction: "in-person", summary: "Annual review meeting", duration: "60 min", by: "Sarah Chen" },
    ],
    goals: [
      { id: 1, name: "Retirement at 67", target: 2500000, current: 1608800, progress: 64, targetDate: "2043-06-30", icon: Target },
      { id: 2, name: "Pay off investment loan", target: 380000, current: 180000, progress: 47, targetDate: "2035-01-01", icon: Home },
      { id: 3, name: "Emergency fund $60K", target: 60000, current: 28000, progress: 47, targetDate: "2027-12-31", icon: DollarSign },
    ],
    family: [
      { name: "David Thompson", relationship: "Primary", dob: "1976-03-15", age: 50 },
      { name: "Sarah Thompson", relationship: "Spouse", dob: "1976-08-22", age: 50 },
    ],
    insurance: [
      { type: "Life", provider: "TAL", sumInsured: 1000000, premium: 1400, premiumFreq: "annual", status: "active" },
      { type: "TPD", provider: "TAL", sumInsured: 750000, premium: 900, premiumFreq: "annual", status: "active" },
      { type: "Income Protection", provider: "OnePath", sumInsured: 10000, premium: 1800, premiumFreq: "annual", status: "active" },
    ],
    keyDates: [
      { date: "2026-05-15", event: "Annual Review Due", type: "review" },
      { date: "2026-03-15", event: "David turns 51", type: "birthday" },
      { date: "2026-08-22", event: "Sarah turns 51", type: "birthday" },
      { date: "2026-06-30", event: "Tax Year End", type: "tax" },
    ],
  },
  client_2: {
    id: "client_2",
    name: "Chen Family Trust",
    email: "michael.chen@email.com",
    phone: "0423 456 789",
    mobile: "0423 456 789",
    address: "15 Pacific Highway, Chatswood NSW 2067",
    status: "active",
    type: "trust",
    clientSince: "2020-08-10",
    dateOfBirth: "1973-04-12",
    age: 52,
    occupation: "Property Developer",
    employer: "Chen Developments",
    riskProfile: "Balanced",
    investmentExperience: "Experienced",
    advisor: "Mark Thompson",
    reviewFrequency: "Semi-Annual",
    lastReview: "2025-09-10",
    nextReview: "2026-02-20",
    satisfaction: 88,
    nps: 8,
    wealth: { total: 5200000, change: -85000, changePercent: -1.6, assetAllocation: { equities: 35, property: 40, fixedIncome: 15, cash: 10 } },
    accounts: [
      { id: 1, name: "Michael Chen Super", type: "Superannuation", institution: "Aware Super", balance: 620000, change: 32000, changePercent: 5.4, icon: PiggyBank },
      { id: 2, name: "Lisa Chen Super", type: "Superannuation", institution: "HESTA", balance: 480000, change: 22000, changePercent: 4.8, icon: PiggyBank },
      { id: 3, name: "Chen Family Trust", type: "Trust", institution: "Macquarie", balance: 2800000, change: -120000, changePercent: -4.1, icon: Building2 },
      { id: 4, name: "Investment Property - Chatswood", type: "Property", institution: "Direct", balance: 1100000, change: 35000, changePercent: 3.3, icon: Home },
      { id: 5, name: "Cash Management", type: "Cash", institution: "CBA", balance: 100000, change: 3000, changePercent: 3.1, icon: DollarSign },
    ],
    transactions: [
      { id: 1, date: "2025-12-12", description: "Trust Distribution - Q4", amount: 45000, type: "income", account: "Chen Family Trust" },
      { id: 2, date: "2025-12-08", description: "Rental Income - Chatswood", amount: 3800, type: "income", account: "Cash Management" },
      { id: 3, date: "2025-12-01", description: "Property Management Fee", amount: -850, type: "expense", account: "Cash Management" },
    ],
    tasks: [
      { id: 1, title: "Trust Tax Return Review", priority: "high", dueDate: "2026-02-20", status: "pending", type: "review" },
      { id: 2, title: "Property Valuation Update", priority: "medium", dueDate: "2026-03-15", status: "pending", type: "planning" },
    ],
    documents: [
      { id: 1, name: "Trust Deed Amendment 2025", type: "Trust", date: "2025-09-10", status: "signed" },
      { id: 2, name: "SOA - Trust Restructure", type: "SOA", date: "2025-09-10", status: "signed" },
    ],
    communications: [
      { id: 1, date: "2025-12-10", type: "email", direction: "outbound", summary: "Sent trust distribution summary", by: "Mark Thompson" },
      { id: 2, date: "2025-11-28", type: "meeting", direction: "in-person", summary: "Tax planning meeting for FY25", duration: "45 min", by: "Mark Thompson" },
    ],
    goals: [
      { id: 1, name: "Retire at 60", target: 6000000, current: 5200000, progress: 87, targetDate: "2033-04-12", icon: Target },
      { id: 2, name: "Children's inheritance", target: 2000000, current: 1400000, progress: 70, targetDate: "2040-01-01", icon: GraduationCap },
    ],
    family: [
      { name: "Michael Chen", relationship: "Primary", dob: "1973-04-12", age: 52 },
      { name: "Lisa Chen", relationship: "Spouse", dob: "1977-09-03", age: 48 },
      { name: "Daniel Chen", relationship: "Son", dob: "2001-06-15", age: 24 },
      { name: "Sophie Chen", relationship: "Daughter", dob: "2005-02-20", age: 20 },
    ],
    insurance: [
      { type: "Life", provider: "AIA", sumInsured: 2000000, premium: 2400, premiumFreq: "annual", status: "active" },
      { type: "Income Protection", provider: "AIA", sumInsured: 20000, premium: 3200, premiumFreq: "annual", status: "active" },
    ],
    keyDates: [
      { date: "2026-02-20", event: "Semi-Annual Review Due", type: "review" },
      { date: "2026-04-12", event: "Michael turns 53", type: "birthday" },
      { date: "2026-06-30", event: "Tax Year End", type: "tax" },
    ],
  },
  client_3: {
    id: "client_3",
    name: "Robert Mitchell",
    email: "r.mitchell@company.com",
    phone: "0434 567 890",
    mobile: "0434 567 890",
    address: "88 King Street, Sydney CBD NSW 2000",
    status: "review",
    type: "individual",
    clientSince: "2017-11-20",
    dateOfBirth: "1967-09-05",
    age: 58,
    occupation: "Senior Executive",
    employer: "BHP Group",
    riskProfile: "Conservative",
    investmentExperience: "Moderate",
    advisor: "Mark Thompson",
    reviewFrequency: "Annual",
    lastReview: "2024-12-15",
    nextReview: "2025-12-20",
    satisfaction: 72,
    nps: 6,
    wealth: { total: 1450000, change: 32000, changePercent: 2.3, assetAllocation: { equities: 30, property: 20, fixedIncome: 35, cash: 15 } },
    accounts: [
      { id: 1, name: "Robert Mitchell Super", type: "Superannuation", institution: "UniSuper", balance: 680000, change: 18000, changePercent: 2.7, icon: PiggyBank },
      { id: 2, name: "Managed Fund Portfolio", type: "Investment", institution: "Colonial First State", balance: 420000, change: 12000, changePercent: 2.9, icon: TrendingUp },
      { id: 3, name: "Investment Unit - Ultimo", type: "Property", institution: "Direct", balance: 280000, change: 5000, changePercent: 1.8, icon: Home },
      { id: 4, name: "Cash Savings", type: "Cash", institution: "Macquarie", balance: 70000, change: 2500, changePercent: 3.7, icon: DollarSign },
    ],
    transactions: [
      { id: 1, date: "2025-12-10", description: "Managed Fund Distribution", amount: 3200, type: "income", account: "Managed Fund Portfolio" },
      { id: 2, date: "2025-12-01", description: "Rental Income - Ultimo", amount: 2200, type: "income", account: "Cash Savings" },
    ],
    tasks: [
      { id: 1, title: "Annual Review - OVERDUE", priority: "urgent", dueDate: "2025-12-20", status: "overdue", type: "review" },
      { id: 2, title: "Retirement Planning Discussion", priority: "high", dueDate: "2026-01-15", status: "pending", type: "planning" },
    ],
    documents: [
      { id: 1, name: "SOA 2024", type: "SOA", date: "2024-12-15", status: "signed" },
      { id: 2, name: "Risk Profile Questionnaire", type: "Assessment", date: "2024-12-10", status: "signed" },
    ],
    communications: [
      { id: 1, date: "2025-11-28", type: "email", direction: "outbound", summary: "Annual review reminder - 3rd attempt", by: "Mark Thompson" },
      { id: 2, date: "2025-10-15", type: "call", direction: "outbound", summary: "Left voicemail about annual review", duration: "2 min", by: "Mark Thompson" },
    ],
    goals: [
      { id: 1, name: "Retire at 65", target: 2000000, current: 1450000, progress: 73, targetDate: "2032-09-05", icon: Target },
    ],
    family: [{ name: "Robert Mitchell", relationship: "Primary", dob: "1967-09-05", age: 58 }],
    insurance: [{ type: "Life", provider: "MLC", sumInsured: 800000, premium: 1400, premiumFreq: "annual", status: "review needed" }],
    keyDates: [
      { date: "2025-12-20", event: "Annual Review - OVERDUE", type: "review" },
      { date: "2026-09-05", event: "Robert turns 59", type: "birthday" },
    ],
  },
  client_4: {
    id: "client_4",
    name: "Emma & David Williams",
    email: "emma.williams@gmail.com",
    phone: "0445 678 901",
    mobile: "0445 678 901",
    address: "23 Elm Street, Balmain NSW 2041",
    status: "prospect",
    type: "household",
    clientSince: "2025-12-01",
    dateOfBirth: "1988-03-20",
    age: 38,
    occupation: "Marketing Director / Software Engineer",
    employer: "Atlassian / David self-employed",
    riskProfile: "TBD",
    investmentExperience: "Beginner",
    advisor: "Mark Thompson",
    reviewFrequency: "TBD",
    lastReview: null,
    nextReview: null,
    satisfaction: null,
    nps: null,
    wealth: { total: 980000, change: 0, changePercent: 0, assetAllocation: { equities: 5, property: 55, fixedIncome: 0, cash: 40 } },
    accounts: [
      { id: 1, name: "David Williams Super", type: "Superannuation", institution: "Australian Retirement Trust", balance: 220000, change: 0, changePercent: 0, icon: PiggyBank },
      { id: 2, name: "Emma Williams Super", type: "Superannuation", institution: "Aware Super", balance: 180000, change: 0, changePercent: 0, icon: PiggyBank },
      { id: 3, name: "Family Home - Balmain", type: "Property", institution: "Direct", balance: 1350000, change: 0, changePercent: 0, icon: Home },
      { id: 4, name: "Mortgage - Balmain", type: "Liability", institution: "ANZ", balance: -880000, change: 0, changePercent: 0, icon: Building2 },
      { id: 5, name: "Joint Savings", type: "Cash", institution: "ING", balance: 45000, change: 0, changePercent: 0, icon: DollarSign },
      { id: 6, name: "Emergency Fund", type: "Cash", institution: "Macquarie", balance: 65000, change: 0, changePercent: 0, icon: DollarSign },
    ],
    transactions: [],
    tasks: [
      { id: 1, title: "Complete Fact Find", priority: "high", dueDate: "2025-12-30", status: "pending", type: "document" },
      { id: 2, title: "Discovery Meeting Follow-up", priority: "high", dueDate: "2025-12-19", status: "pending", type: "meeting" },
      { id: 3, title: "Prepare Initial SOA", priority: "medium", dueDate: "2026-01-20", status: "pending", type: "document" },
    ],
    documents: [{ id: 1, name: "Discovery Meeting Notes", type: "Notes", date: "2025-12-12", status: "completed" }],
    communications: [
      { id: 1, date: "2025-12-12", type: "meeting", direction: "in-person", summary: "Discovery meeting - discussed goals, risk appetite, and current financial position", duration: "1.5 hr", by: "Mark Thompson" },
    ],
    goals: [
      { id: 1, name: "Build investment portfolio", target: 500000, current: 0, progress: 0, targetDate: "2030-01-01", icon: Target },
      { id: 2, name: "Kids' education fund", target: 150000, current: 0, progress: 0, targetDate: "2034-01-01", icon: GraduationCap },
      { id: 3, name: "Pay off mortgage faster", target: 880000, current: 0, progress: 0, targetDate: "2040-01-01", icon: Home },
    ],
    family: [
      { name: "David Williams", relationship: "Primary", dob: "1988-03-20", age: 38 },
      { name: "Emma Williams", relationship: "Spouse", dob: "1990-07-14", age: 36 },
      { name: "Lily Williams", relationship: "Daughter", dob: "2018-01-10", age: 8 },
      { name: "Jack Williams", relationship: "Son", dob: "2021-04-22", age: 5 },
    ],
    insurance: [],
    keyDates: [
      { date: "2025-12-19", event: "Discovery Follow-up", type: "meeting" },
      { date: "2026-01-20", event: "SOA Presentation", type: "document" },
    ],
  },
  client_5: {
    id: "client_5",
    name: "Patel SMSF",
    email: "raj.patel@business.com.au",
    phone: "0456 789 012",
    mobile: "0456 789 012",
    address: "5/120 George Street, Parramatta NSW 2150",
    status: "active",
    type: "smsf",
    clientSince: "2018-05-15",
    dateOfBirth: "1978-01-08",
    age: 48,
    occupation: "Business Owner - IT Services",
    employer: "Patel IT Solutions Pty Ltd",
    riskProfile: "Aggressive",
    investmentExperience: "Very Experienced",
    advisor: "Mark Thompson",
    reviewFrequency: "Quarterly",
    lastReview: "2025-12-08",
    nextReview: "2026-03-15",
    satisfaction: 92,
    nps: 9,
    wealth: { total: 3100000, change: 180000, changePercent: 6.2, assetAllocation: { equities: 55, property: 20, fixedIncome: 10, cash: 15 } },
    accounts: [
      { id: 1, name: "Patel SMSF", type: "SMSF", institution: "Macquarie", balance: 2400000, change: 150000, changePercent: 6.7, icon: Shield },
      { id: 2, name: "Business Account", type: "Business", institution: "NAB", balance: 500000, change: 25000, changePercent: 5.3, icon: Building2 },
      { id: 3, name: "Cash Reserve", type: "Cash", institution: "ING", balance: 200000, change: 5000, changePercent: 2.6, icon: DollarSign },
    ],
    transactions: [
      { id: 1, date: "2025-12-10", description: "SMSF Contribution - Raj", amount: 25000, type: "contribution", account: "Patel SMSF" },
      { id: 2, date: "2025-12-05", description: "Dividend - ASX Portfolio", amount: 8500, type: "income", account: "Patel SMSF" },
    ],
    tasks: [
      { id: 1, title: "SMSF Annual Audit", priority: "medium", dueDate: "2026-03-15", status: "pending", type: "compliance" },
    ],
    documents: [
      { id: 1, name: "SMSF Investment Strategy 2025", type: "IPS", date: "2025-12-08", status: "current" },
      { id: 2, name: "SMSF Audit Report 2024", type: "Audit", date: "2025-03-10", status: "completed" },
    ],
    communications: [
      { id: 1, date: "2025-12-08", type: "meeting", direction: "video", summary: "Quarterly SMSF review - discussed tech sector allocation", duration: "40 min", by: "Mark Thompson" },
    ],
    goals: [
      { id: 1, name: "SMSF to $5M", target: 5000000, current: 2400000, progress: 48, targetDate: "2035-01-01", icon: Target },
      { id: 2, name: "Sell business by 55", target: 3000000, current: 500000, progress: 17, targetDate: "2033-01-08", icon: Building2 },
    ],
    family: [
      { name: "Raj Patel", relationship: "Primary", dob: "1978-01-08", age: 48 },
      { name: "Priya Patel", relationship: "Spouse", dob: "1981-05-22", age: 45 },
      { name: "Aarav Patel", relationship: "Son", dob: "2003-11-10", age: 22 },
    ],
    insurance: [
      { type: "Life", provider: "Zurich", sumInsured: 3000000, premium: 3800, premiumFreq: "annual", status: "active" },
      { type: "Key Person", provider: "Zurich", sumInsured: 2000000, premium: 2800, premiumFreq: "annual", status: "active" },
    ],
    keyDates: [
      { date: "2026-03-15", event: "Quarterly Review & SMSF Audit", type: "review" },
      { date: "2026-01-08", event: "Raj turns 48", type: "birthday" },
    ],
  },
};

// Aliases for client IDs used by other components
DEMO_CLIENT_DATA.thompson_family = DEMO_CLIENT_DATA.client_1;
DEMO_CLIENT_DATA.chen_family = DEMO_CLIENT_DATA.client_2;
